### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [5]:
!pip install tensorflow

In [6]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [33]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [35]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [36]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [37]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[3367, 7886, 8635, 418], [3367, 7886, 8635, 6124], [3367, 5587, 8635, 1041], [9504, 1802, 5944, 8537, 6323], [9504, 1802, 5944, 8537, 922], [3199, 3367, 9219, 8635, 1852], [8222, 1162, 7669, 8537]]


### Word Embedding Represntation

In [38]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [40]:
import numpy as np

In [43]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3367 7886 8635  418]
 [   0    0    0    0 3367 7886 8635 6124]
 [   0    0    0    0 3367 5587 8635 1041]
 [   0    0    0 9504 1802 5944 8537 6323]
 [   0    0    0 9504 1802 5944 8537  922]
 [   0    0    0 3199 3367 9219 8635 1852]
 [   0    0    0    0 8222 1162 7669 8537]]


In [44]:
## post padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3367 7886 8635  418    0    0    0    0]
 [3367 7886 8635 6124    0    0    0    0]
 [3367 5587 8635 1041    0    0    0    0]
 [9504 1802 5944 8537 6323    0    0    0]
 [9504 1802 5944 8537  922    0    0    0]
 [3199 3367 9219 8635 1852    0    0    0]
 [8222 1162 7669 8537    0    0    0    0]]


In [46]:
## 10 feature dimesnions
dim=10


In [45]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [47]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [53]:
##'the glass of milk',
embedded_docs[4]

array([9504, 1802, 5944, 8537,  922,    0,    0,    0], dtype=int32)

In [54]:
model.predict(embedded_docs[3])

1/1 [==============================] - 0s 16ms/step


array([[ 0.04423536,  0.02633791,  0.04896757, -0.04503116,  0.014534  ,
        -0.01361825, -0.00557037, -0.02183261, -0.04261333, -0.03911743],
       [ 0.03930134,  0.03682731, -0.04064239, -0.00846182,  0.01281205,
         0.02003117, -0.0055423 ,  0.04043357,  0.04230504, -0.00625316],
       [ 0.0175201 ,  0.00333275,  0.03283078,  0.01309801, -0.0212248 ,
         0.03392472,  0.04716126,  0.02898622, -0.04584038,  0.04927167],
       [-0.00757723,  0.01891995, -0.03048165,  0.03222534,  0.03180664,
        -0.04052915, -0.01168315,  0.00076674,  0.02312252,  0.00059726],
       [-0.0225722 ,  0.04772944,  0.00915947,  0.00743442, -0.04884659,
        -0.03281226, -0.03663136, -0.0026706 ,  0.00927722,  0.03955083],
       [-0.02313911,  0.02033787, -0.01309367,  0.03325028, -0.02931094,
        -0.02426287, -0.02650371,  0.01598126, -0.03138836,  0.00353681],
       [-0.02313911,  0.02033787, -0.01309367,  0.03325028, -0.02931094,
        -0.02426287, -0.02650371,  0.01598126

In [55]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 33ms/step
[[[ 4.03289907e-02  4.36372682e-03  4.31119464e-02 -8.67471099e-05
    2.20794603e-03  3.69046368e-02  1.41865648e-02  1.48455240e-02
    3.59632708e-02 -2.89721247e-02]
  [-2.83253547e-02 -4.58765626e-02 -2.64843553e-03  1.01584196e-03
    8.71369988e-03  1.78874768e-02 -2.26442218e-02 -3.96317355e-02
   -1.73427090e-02  1.59677602e-02]
  [-2.97713634e-02 -1.30168572e-02 -3.13440450e-02 -4.90135215e-02
   -7.21202046e-03 -3.30568776e-02  1.56986974e-02  1.68313123e-02
    3.97548191e-02  2.98248865e-02]
  [ 1.35678761e-02 -4.37009931e-02  4.51709889e-02 -2.46007685e-02
   -2.28012092e-02 -4.15394679e-02  2.71145739e-02  1.33769587e-03
    2.13519819e-02 -1.24359131e-02]
  [-2.31391080e-02  2.03378685e-02 -1.30936727e-02  3.32502760e-02
   -2.93109417e-02 -2.42628697e-02 -2.65037064e-02  1.59812607e-02
   -3.13883573e-02  3.53680924e-03]
  [-2.31391080e-02  2.03378685e-02 -1.30936727e-02  3.32502760e-02
   -2.93109417e-02 -2.42628697e

In [21]:
embedded_docs[0]

array([  0,   0,   0,   0, 299, 163,  47, 399], dtype=int32)

In [22]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 18ms/step
[[-0.0433107  -0.02927794 -0.0093125  -0.02345903  0.03243983  0.01923375
  -0.02217627  0.00746355 -0.00659268 -0.01812824]
 [-0.0433107  -0.02927794 -0.0093125  -0.02345903  0.03243983  0.01923375
  -0.02217627  0.00746355 -0.00659268 -0.01812824]
 [-0.0433107  -0.02927794 -0.0093125  -0.02345903  0.03243983  0.01923375
  -0.02217627  0.00746355 -0.00659268 -0.01812824]
 [-0.0433107  -0.02927794 -0.0093125  -0.02345903  0.03243983  0.01923375
  -0.02217627  0.00746355 -0.00659268 -0.01812824]
 [-0.04188093 -0.00321103  0.04571855 -0.04112945 -0.0316216   0.01648252
   0.01715614  0.02464398 -0.01411443 -0.04350295]
 [ 0.00780531  0.00323149 -0.03460763 -0.02945776  0.01351461 -0.00506882
  -0.02152379  0.04034476  0.01072286 -0.02994479]
 [ 0.02600565 -0.0306326   0.03594592  0.02372554 -0.04865494 -0.01098096
   0.03109573 -0.00678707  0.01804345 -0.03800644]
 [-0.01227386  0.0242026   0.03031658 -0.02822687  0.04615164  0.01890118

In [60]:
### Assignment

sent1=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [61]:
### Vocabulary size
voc_size=10000

In [65]:
onehot_repr=[one_hot(words,voc_size)for words in sent1]
print(onehot_repr)

[[3367, 4264, 3264, 5944, 5558, 443], [6166, 429, 3264, 5395, 2594, 2923], [9504, 6094, 3922, 6143], [3367, 376, 3264, 7554, 3367, 2627], [9882, 9734, 4416, 3264, 5395, 2594, 2923], [5446, 3264, 5395, 2594, 5708, 6030]]


In [66]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [67]:
import numpy as np
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0 3367 4264 3264 5944 5558  443]
 [   0    0 6166  429 3264 5395 2594 2923]
 [   0    0    0    0 9504 6094 3922 6143]
 [   0    0 3367  376 3264 7554 3367 2627]
 [   0 9882 9734 4416 3264 5395 2594 2923]
 [   0    0 5446 3264 5395 2594 5708 6030]]


In [68]:
# Adding the dimensions
dim=10

In [69]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [70]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [71]:
##'the glass of milk',
embedded_docs[4]

array([   0, 9882, 9734, 4416, 3264, 5395, 2594, 2923], dtype=int32)

In [72]:
model.predict(embedded_docs[3])

1/1 [==============================] - 0s 37ms/step


array([[ 0.02024652,  0.04356459,  0.04555105,  0.0279071 , -0.02243077,
        -0.02078091, -0.00143407, -0.03070079, -0.02325794,  0.03570486],
       [ 0.02024652,  0.04356459,  0.04555105,  0.0279071 , -0.02243077,
        -0.02078091, -0.00143407, -0.03070079, -0.02325794,  0.03570486],
       [ 0.04795024, -0.01503729, -0.03668739, -0.00780616, -0.01182822,
        -0.04477339,  0.01096752, -0.04075346, -0.00804453, -0.0392893 ],
       [-0.03513057, -0.03213588, -0.04271021,  0.03497188,  0.01538188,
        -0.04513296,  0.01310616, -0.01736725,  0.02280502, -0.03928643],
       [-0.0089262 ,  0.0149082 ,  0.02473878, -0.04442638, -0.03377761,
         0.01917937,  0.0097362 , -0.02635781,  0.0273529 , -0.03687475],
       [-0.02127168, -0.0216242 , -0.00597107,  0.01493008,  0.02286491,
         0.00840624, -0.0284374 , -0.02359743,  0.03053919, -0.03240891],
       [ 0.04795024, -0.01503729, -0.03668739, -0.00780616, -0.01182822,
        -0.04477339,  0.01096752, -0.04075346